- name: Create a new database with name "os_commands"
  community.postgresql.postgresql_db:
    name: "{{ db.name }}"
    #encoding: UTF-8
    state: present

- name: Create user, set MD5-hashed password, grant privs
  community.postgresql.postgresql_user:
    db: "{{ db.name }}"
    name: "{{ db.user }}"
    password: "{{ db.password | password_hash('md5') }}"
    role_attr_flags: CREATEDB,NOSUPERUSER