- name: "find initdb"
  shell: "find / -iname initdb -type f 2>/dev/null"
  register: initdb
  ignore_errors: yes
  tags: initialization 

- name: Show result of initdb
  debug:
    var: initdb.stdout_lines[0]
  tags: initialization  

- name: Create a symbolic link
  ansible.builtin.file:
    src: "{{ initdb.stdout_lines[0] }}"
    dest: /usr/local/bin/initdb
    state: link
  tags: initialization 

- name: Ensure PostgreSQL data directory exists.
  file:
    path: "{{ postgresql_data_dir }}"
    state: directory
    owner: "{{ postgresql_user }}"
    mode: 0700
  tags: initialization

- name: Ensure PostgreSQL database is initialized.
  command: "initdb -D {{ postgresql_data_dir }}"  
  become: true
  become_user: "{{ postgresql_user }}"
  tags: initialization