---
- name: PostgreSQL. Install packages
  ansible.builtin.apt:
    name: "{{ packages.postgresql }}"
    state: latest #absent 
    update_cache: true
  environment:
    DEBIAN_FRONTEND: noninteractive
  tags: install
  
- name: "Install Python packages"
  ansible.builtin.apt:
    name: "{{ packages.python }}"
    state: latest #absent 
    update_cache: true
  tags: install

- name: "find path to pg_hba.conf"
  shell: "find / -iname pg_hba.conf -type f 2>/dev/null"
  register: pg_hba
  ignore_errors: yes
  tags: init

- name: "Find out if PostgreSQL is initialized"
  ansible.builtin.stat:
    path: "{{ pg_hba.stdout_lines[0] }}"
  register: postgres_data
  tags: init
