name: psql install (ansible)
on: [ workflow_dispatch ] #push 
jobs:
  psql_install:
    runs-on: ubuntu-latest  
    steps:       
      - name: SSH connect to remoute host and run playbook
        id: psql
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          proxy_host: ${{ secrets.PROXY_HOST }}
          proxy_username: ${{ secrets.PROXY_USERNAME }}
          proxy_key: ${{ secrets.PROXY_KEY }}
          proxy_port: ${{ secrets.PROXY_PORT }} #-v          
          script: |
            cd /root/progect/ansible/role/
            ansible-playbook run_psql_install_role.yaml > /root/ansible_logs.txt
      
      - name: Download file via SSH
        uses: nicklasfrahm/scp-action@main
        with:
          direction: download
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          insecure_ignore_fingerprint: true
          port: ${{ secrets.PORT }}
          proxy_host: ${{ secrets.PROXY_HOST }}
          proxy_fingerprint: true
          proxy_username: ${{ secrets.PROXY_USERNAME }}
          proxy_key: ${{ secrets.PROXY_KEY }}
          proxy_port: ${{ secrets.PROXY_PORT }}
          insecure_proxy_ignore_fingerprint: true
          source: "/root/ansible_logs.txt"
          target: "./logs.log"
            
      - name: Upload Crashed Pods List k3s 
        uses: actions/upload-artifact@v4
        with:
            name: Failed pods 
            path: ./logs.log
      
      - name: Slack notification 
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: alarm_channel
          SLACK_COLOR: 'red'
          SLACK_USERNAME: helm-page
          SLACK_TITLE: "NEW Helm Page was creted! Version ${{needs.docker-build.outputs.tag}}"
          SLACK_WEBHOOK: ${{ secrets.WEBHOOK_SLACK}}  